### ISSUE TITLE
Allow further configuration of the http client on `AddReCaptcha` service collection extensions

### ISSUE THREAD

**Issue by msschl** [michaelvs97/AspNetCore.ReCaptcha#28]
We do want to configure the underlying httpclient to add some Polly backoff strategies and circuit breakers. However, the `IHttpClientBuilder` returned by `AddHttpClient` is currently not exposed to further configuration.

Please consider an overload in `AddReCaptcha(this IServiceCollection services, Action<ReCaptchaSettings> configureOptions)` taking in an Action<IHttpClientBuilder> to further configure the httpclient.

**Comment by sleeuwen** [comment]
Thanks for suggesting this, this looks like a good enhancement and it's now been implemented in version 1.5.0 that should be available shortly on nuget.
