### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by kendesha** [michaelvs97/AspNetCore.ReCaptcha#31]
Hi guys. I am trying to use your package but I have a question. How do I tell if the validation on the recaptcha was a success or not ?
I added the [ValidateReCaptcha] class over my method but I want to get the response. Also I am trying to implement the recaptcha on two different parts of my website. One post data straight to the controller and another post data to the controller using ajax. How can I handle this?. Please help

**Comment by sleeuwen** [comment]
Hi, using the `[ValidateReCaptcha]` attribute will automatically validate the recaptcha and add a validation error to the `ModelState`. If you rather want to validate the recaptcha yourself you can inject the `IReCaptchaService` and call it's `VerifyAsync` method, this will return a `bool` whether the validation succeeded or not.

**Comment by kendesha** [comment]
Thank you so much for clarifying!.
