### ISSUE TITLE
V3 Samples not working

### ISSUE THREAD

**Issue by VictorioBerra** [michaelvs97/AspNetCore.ReCaptcha#35]
**Describe the bug**
I found that my code did not work, so I pulled the samples, and they dont work either.

Clone samples, run net6.0 sample, notice no recap on the Contact page. V2 sample works.

**To Reproduce**
1. Clone samples
2. Change GetSection in Startup to ReCaptchaV3
3. Launch sample
4. Click Contact, no ReCaptcha.

**Expected behavior**
You should see a ReCaptcha

**Screenshots**
![image](https://user-images.githubusercontent.com/2934507/155794870-ad79b401-49c6-44fe-acfa-815eabc2825c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  98.0.4758.102

**Additional context**
V2 Sample configuration works.

**Comment by sleeuwen** [comment]
Hi, the observed behavior is correct and this is how V2invisible and V3 are supposed to work. These versions don't have a checkbox you need to click on but instead are called just before the form is submitted to determine whether a captcha prompt is necessary. With these versions there is a recaptcha badge in the bottom right corner that indicates that recaptcha is active. I'd recommend you check out the google recaptcha docs on the different versions and how they work.

**Comment by VictorioBerra** [comment]
Ahh thanks so much.
