### ISSUE TITLE
ReCaptchaResponse.Score and ReCaptchaSettings.ScoreThreshold are different types resulting in unpredictable behavior

### ISSUE THREAD

**Issue by Driedas** [michaelvs97/AspNetCore.ReCaptcha#37]
**Describe the bug**
as per the title, ReCaptchaResponse.Score is defined as a double whereas ReCaptchaSettings.ScoreThreshold is defined as a float (single), resulting in unpredictable behavior. As an example, I used a value of 0.1 for the threshold parameter, and have received a 0.1 from the recaptcha service:
![image](https://user-images.githubusercontent.com/7829690/158448021-4530f466-d274-4ff2-90b8-e79fcea7325c.png)

Both have a logical value of 0.1, however the float value has to be converted to a double for comparison, which yields a possibly unexpected result:
![image](https://user-images.githubusercontent.com/7829690/158448552-de796eae-306f-4135-8dfa-18c0569cc716.png)

**To Reproduce**
1. try a 
```
Console.WriteLine((double)(float)0.1);
```
line in a console project

or 

1. try the following REPL https://replit.com/@PavelSteinl/PeskyLovingLine#main.cs

**Expected behavior**
Both properties should be of the same type as they represent semantically the same value. The correct type would probably be a decimal as the number is a rational number with a fixed number of decimals.

**Screenshots**
See screenshots in text above

**Desktop (please complete the following information):**
Doesn't matter

**Comment by sleeuwen** [comment]
Thanks @Driedas for reporting the issue and figuring out what the problemwas. I've changed the ScoreThreshold to a double and published v1.5.3 to nuget which should be available shortly

**Comment by Driedas** [comment]
super quick as usual guys, thanks!
