### ISSUE TITLE
How can I see the response from google?

### ISSUE THREAD

**Issue by CyberBitz** [michaelvs97/AspNetCore.ReCaptcha#42]
I am trying to add it to my net6 core razor site and looking to see the response from google or what object it may be in the ModelState.IsValid properties. For some reason it dosent seem to be working.

**Comment by sleeuwen** [comment]
When you use the `[ValidateReCaptcha]` attribute it adds an error message to the `ModelState` with the key "Recaptcha" when the response indicates the recaptcha wasn't successful. If you need to get the verification response you can instead inject the `IReCaptchaService` in your page/controller and call `IReCaptchaService.GetVerifyResponseAsync()` passing it the value from the recaptcha as the only argument (by default it is in the form field "g-recaptcha-response"). The object returned from that method is the deserialized response from google.
