### ISSUE TITLE
Cannot get it to work with Ajax form

### ISSUE THREAD

**Issue by ccasalicchio** [michaelvs97/AspNetCore.ReCaptcha#52]
**Describe the bug**
The form is submitted via ajax (post) but it keeps returning "Your request cannot be completed because you failed Recaptcha verification."

**To Reproduce**

      "ReCaptcha": {
        "SiteKey": "KEY",
        "SecretKey": "Key",
        "Version": "v2"
      },

		<div class="card card-body">
			<form class="form-home" id="contact-form">
				<div asp-validation-summary="All"></div>
				<div class="row">

					<div class="col-12 col-sm-5 offset-sm-1">
						<input class="form-control" type="text" placeholder="Nombre y Apellido" name="name" required>
					</div>
					<div class="col-12 col-sm-5">
						<input class="form-control" type="email" placeholder="E-mail" name="email" required>
					</div>
					<div class="col-12 col-sm-5 offset-sm-1">
						<input class="form-control" type="tel" placeholder="Teléfono" name="phone">
					</div>
					<div class="col-12 col-sm-5">
						<select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="reason">
							<option selected>Motivo</option>
							<option value="Sugerencia">Sugerencia</option>
							<option value="Reclamo">Reclamo</option>
							<option value="Contratar un seguro">Contratar un seguro</option>
						</select>
					</div>
					<div class="col-12 col-sm-10 offset-sm-1">
						<textarea class="form-control" id="exampleFormControlTextarea1" rows="5" placeholder="Comentarios" name="message" required></textarea>
					</div>

					<div class="col-12 col-sm-10 offset-sm-1 mt-3 align-center">
						@Html.ReCaptcha()
					</div>

					<div class="col-12">
						<button class="btn-cancelar mt-4" type="button">CANCELAR</button>  <button class="btn-enviar mt-4" type="submit">ENVIAR</button>
					</div>
				</div>
			</form>
			<br />
			<div id="submitted-message">Gracias, su mesaje fue enviada!</div>
			<div id="error-message">Favor llenar todos los campos!</div>
		</div>

            [ValidateReCaptcha]
            [HttpPost]
            public async Task<IActionResult> Submit([FromBody]ContactFormModel model)
            {
                if (!ModelState.IsValid)
                    return BadRequest();

                return Ok(model);
            }
        

    document.addEventListener('DOMContentLoaded', () => {
        let form = document.getElementById('contact-form');
        if (form !== null) {
            form.addEventListener('submit', f => {
                $("#contact-form").validate();
                f.preventDefault();
                var formData = {
                    name: $("input[name=name]").val(),
                    email: $("input[name=email]").val(),
                    phone: $("input[name=phone]").val(),
                    reason: $("[name=reason]").val(),
                    message: $("[name=message]").val(),
                };
                $.ajax({
                    type: "POST",
                    url: "/Umbraco/Api/Contact/Submit",
                    data: JSON.stringify(formData),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    encode: true,
                }).done(function (data) {
                    if (data.success) {
                        $('#error-message').fadeOut();
                        $('#contact-form').fadeOut();
                        $('#submitted-message').fadeIn();
                    }
                }).error(() => {
                    $('#error-message').fadeIn();
                });

            })
        }
    })

**Expected behavior**
recaptcha validation should work

**Screenshots**
![image](https://user-images.githubusercontent.com/2466879/193301959-636dfcc1-9682-49e5-b9f1-1861c3a9f4c8.png)

Chrome Browser

**Comment by sleeuwen** [comment]
The recaptcha implementation will generate an extra input field which will contain the verification token that needs to be validated with the recaptcha server. This field is automatically send when the form is submitted, but because you create the request body manually it does not include this token and cannot verify if it is valid.

You should add the value from that generates input field in your request body to get it to validate correctly.

**Comment by ccasalicchio** [comment]
![image](https://user-images.githubusercontent.com/2466879/193480891-f933447f-7606-4728-9556-ee3978b22ae8.png)
It's now sending the token, but the validation still fails.

**Comment by nwoolls** [comment]
@ccasalicchio AFAICS the `[ValidateReCaptcha]` attribute works with form data, not JSON. But you should be able to use the `ReCaptchaService` class directly instead of the `[ValidateReCaptcha]` attribute.

Alternatively, you could update your `POST` to use `application/x-www-form-urlencoded` instead of JSON, which should work with the `[ValidateReCaptcha]` attribute.

**Comment by sleeuwen** [comment]
This is correct, we only support form data for the attribute, this is because the request body can only be read once which will be when it's bound to the model. I've expanded the readme how you can use the `IReCaptchaService` directly to verify the response in this case.
