### ISSUE TITLE
Disable ReCaptcha for development

### ISSUE THREAD

**Issue by VictorioBerra** [michaelvs97/AspNetCore.ReCaptcha#53]
**Is your feature request related to a problem? Please describe.**
I would like to disable ReCaptcha when `environment.IsDevelopment() == true`

**Describe the solution you'd like**
I would like a bool in [ReCaptchaSettings](https://github.com/michaelvs97/AspNetCore.ReCaptcha/blob/master/AspNetCore.ReCaptcha/ReCaptchaSettings.cs) called Enabled.

**Describe alternatives you've considered**
Is it possible for me to skip calling `services.AddReCaptcha(this.Configuration.GetSection("ReCaptcha")` in development, and that will not break anything? Even though I still have the tag helpers, and the attributes on my Razor Pages?

**Additional context**

**Comment by nwoolls** [comment]
@VictorioBerra FWIW I've submitted a PR for a feature such as this here:

* https://github.com/michaelvs97/AspNetCore.ReCaptcha/pull/56

**Comment by VictorioBerra** [comment]
Thank you!!
