### ISSUE TITLE
Enable INFO logging of recaptcha response

### ISSUE THREAD

**Issue by fatemeh-freemarket** [michaelvs97/AspNetCore.ReCaptcha#58]
**Is your feature request related to a problem? Please describe.**
We are not able to monitor our users' ReCaptcha level - version `v1.7.0`

**Describe the solution you'd like**
It would be great to see ReCaptcha logging response in order to monitor  the levels.

**Describe alternatives you've considered**
NA

**Additional context**
At the moment I have come across this line in your [solution](https://github.com/michaelvs97/AspNetCore.ReCaptcha/blob/master/AspNetCore.ReCaptcha/ReCaptchaService.cs#L60):
```
 _logger?.LogTrace("recaptcha response: {recaptchaResponse}", stringResult);
```
However, I cannot see scores recieved by Google Recaptcha response.
logging response would help integrate with monitoring platforms 

Thank you.

**Comment by sleeuwen** [comment]
Hi,

As you already found, we log the full response that is received from the recaptcha service as trace level. If you use recaptcha v3 this also includes the score.

If you want to see these logs you can set the log level for "AspNetCore.ReCaptcha.ReCaptchaService" to trace in your appsettings. If you're using Microsoft.Extensions.Logging that can be done like this:
```json
{
  "Logging": {
    "LogLevel": {
      "AspNetCore.ReCaptcha.ReCaptchaService": "Trace"
    }
  }
}
```

**Comment by parkinsona** [comment]
I found the reason for my log not including scores. This was occurring because it was hitting the server side, before it had finished loading the recaptcha response token in the hidden field. So it meant it was trying to validate an empty tag.

**Comment by michaelvs97** [comment]
Closing this issue, since its seems to not related to the package. Please re-open if you feel it's unrightly closed.
