### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by durmisi** [michaelvs97/AspNetCore.ReCaptcha#6]
Hello Michael,

I would like to ask you about the language support, analyzed the code a bit and found that the language parameter is not using yet.

What are you plans for adding language support?

Thanks

**Comment by michaelvs97** [comment]
Hello Admir,

We are planning to add language support in the next release of the library.
We are planning to automatically use the current request language for the response, but we will also provide the option to overrule this setting by providing a language in the `@Html.ReCaptcha()` helper.

Regards,
Michael

**Comment by michaelvs97** [comment]
Hello Admir,

Last friday we released version 1.1.0 where this is implemented, documentation is now also up to date to make use of this feature. If you got any questions, feel free to contact me.

Regards,
Michael
