### ISSUE TITLE
Using IOptionsSnapshot in ReCaptchaService

### ISSUE THREAD

**Issue by andbaz** [michaelvs97/AspNetCore.ReCaptcha#64]
In some cases, you would like to dynamically manage the AspNetCore.ReCaptcha configuration.
For example, SAAS clients want to manage their SecretKey and SiteKey through the administration page.

ReCaptchaTagHelper uses IOptionsSnapshot<ReCaptchaSettings>. This is wonderful.
I would like ReCaptchaService to use this too.

I understand the problem with pre-configuring HttpCLient with BaseUrl. This is only about SecretKey and SiteKey.

**Comment by sleeuwen** [comment]
Hi @andbaz, Thanks for the suggestion, I actually found some places that had different behavior in case the options changed which I've fixed as well.

**Comment by andbaz** [comment]
thx
