### ISSUE TITLE
how to add additional styling? eg width etc...

### ISSUE THREAD

**Issue by joseph-ts** [michaelvs97/AspNetCore.ReCaptcha#68]
Setting the width would be a great feature for presentations. Or maybe just enter the component on a div

**Comment by sleeuwen** [comment]
Google ReCaptcha only supports a "size" attribute which can be set to either "normal" or "compact". You can provide the `size` attribute when using the taghelper like `<recaptcha size="normal" />`.  If you use a different way to render the component that should also take a `size` parameter.
There is no other officially supported way to change the size of the widget, and we will only support the officially supported parameters.
